# /// script
# requires-python = "==3.14.*"
# dependencies = []
# ///

"""Dispatch a host launcher using configuration generated by Nix"""

from __future__ import annotations

import io
import json
import os
import signal
import subprocess
import sys
from pathlib import Path

# Import only the adjacent pinned modules, even with Python's isolated mode
sys.path.insert(0, str(Path(__file__).resolve().parent))

from arm64 import Arm64Launcher  # noqa: E402
from common import LauncherError  # noqa: E402
from configuration import parse_configuration  # noqa: E402
from fex import FexLauncher  # noqa: E402


def main() -> int:
    if isinstance(sys.stdout, io.TextIOWrapper):
        sys.stdout.reconfigure(line_buffering=True)
    try:
        if os.geteuid() == 0:
            raise LauncherError("Do not run steam-asahi as root")
        with open(sys.argv[1], encoding="utf-8") as source:
            configuration = parse_configuration(json.load(source))
        if configuration["BACKEND"] == "arm64":
            launcher = Arm64Launcher(configuration)
        else:
            launcher = FexLauncher(configuration)
        launcher.main(sys.argv[2:])
    except KeyboardInterrupt:
        signal.signal(signal.SIGINT, signal.SIG_DFL)
        os.kill(os.getpid(), signal.SIGINT)
    except subprocess.CalledProcessError as error:
        if error.returncode < 0:
            # Preserve a helper's signal termination instead of wrapping it
            signum = -error.returncode
            if signum not in (signal.SIGKILL, signal.SIGSTOP):
                signal.signal(signum, signal.SIG_DFL)
            os.kill(os.getpid(), signum)
        return error.returncode
    except (LauncherError, OSError, ValueError, KeyError, IndexError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
